apps/posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('<slug:title>/', views.ThreadListView.as_view(), name='thread_list'),
    path('<slug:title>/thread/<slug:comment_slug>/', views.ThreadDetailView.as_view(), name='thread_detail'),
    path('comment/reply-to/<uuid:pk>/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/edit/<uuid:pk>/', views.CommentEditView.as_view(), name='comment_edit'),
    path('thread/create/<str:category>', views.ThreadCreateView.as_view(), name='thread_create'),
    path('user/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('categories/all/', views.CatListView.as_view(), name='category_list'),
    path('categories/create/', views.CatCreateView.as_view(), name='category_create'),
    path('djreddit/search/', views.DjredditSearchView.as_view(), name='djreddit_search'),
    path('djreddit/subscription/<str:category>/', views.SubscriptionView.as_view(), name='djreddit_sub'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('topic/', include("apps.topics.urls")),
    path('', include("apps.posts.urls", namespace="posts")),
    path('vote/', include("apps.votes.urls")),
]

apps/templates/auth_base.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">{% block head %}{% endblock head %}</h3></div>
                                    <div class="card-body">
                                            {% block form %}
                                            {% endblock form %}
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small">{% block link %}{% endblock link %}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </body>
</html>

apps/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}{% endblock title %}
        </title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    </head>

    <body>
        <nav class="navbar bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'posts:homepage' %}">Djreddit</a>
                 <!-- Navbar Search-->
                <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" method="get" action="{% url 'posts:djreddit_search' %}">
                    <div class="input-group">
                        <input class="form-control" type="text" name="q" placeholder="Search for Djreddit..." aria-label="Search for Djreddit..." aria-describedby="btnNavbarSearch" />
                        <button class="btn btn-primary" id="btnNavbarSearch" type="submit">Go!</button>
                    </div>
                </form>
                <!-- Account Navbar-->
                <div class="dropdown-center ms-auto ms-md-0 me-3 me-lg-4">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-offset="10,20">
                        {% if user.username %}
                        {{user.username}}
                        {% else %}
                        Login
                        {% endif %}
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        {% if user.is_authenticated %}
                        <li class="dropdown-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="dropdown-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        <li class="dropdown-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <!-- Navbar-->
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                            {% if user.is_authenticated %}
                                Hello {{ user.username }} !
                            {% else %}
                                Welcome to Djreddit
                            {% endif %}
                        </h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'posts:homepage' %}">Home</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'posts:user_profile' user.username %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'posts:thread_create' category='nocategory' %}">Create a New Thread</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'posts:category_create'%}">Create New Category</a>
                            </li>
                            {% endif %}

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Categories
                                </a>
                                <ul class="dropdown-menu">
                                    <form class="d-flex" role="search">
                                        <input class="form-control me-2" type="search" placeholder="Search Categories" aria-label="Search">
                                        <button class="btn btn-outline-success" type="submit">Search</button>
                                    </form>
                                    {% if subscribed_categories %}
                                        {% for category in subscribed_categories %}
                                            <li><a class="dropdown-item" href="{% url 'posts:thread_list' category.title %}">{{category}}</a></li>
                                        {% endfor %}
                                    {% else %}
                                        <li><a class="dropdown-item" href="{% url 'posts:category_list' %}">Explore Categories</a></li>
                                    {% endif %}
                                   </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <!-- header block-->
        <div class="pt-5">
            {% block header %}
            {% endblock header %}
        </div>

        <!-- content block-->
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    {% block content %}
                    {% endblock content%}
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">What's on your mind?</div>
                        <div class="card-body">
                            {% if user.is_authenticated %}
                            <ul class="list-unstyled mb-1">
                                <button class="btn btn-outline-primary">
                                    <a class="nav-link" href="{% url 'posts:thread_create' category='nocategory' %}">Create a New Thread</a>
                                </button>
                            </ul>
                            <ul class="list-unstyled mb-1">
                                <button class="btn btn-outline-primary">
                                    <a class="nav-link" href="{% url 'posts:category_create'%}">Create a New Category</a>
                                </button>
                            </ul>
                            {% endif %}
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <ul class="list-unstyled mb-0">
                                        {% for category in categories %}
                                        <div class="row">
                                            <div class="col-sm-4">
                                                <li><a href="{% url 'posts:thread_list' category.title %}">{{category}}</a></li>
                                            </div>
                                            <div class="col-sm-4">
                                                {% if category in user.get_subscribed %}
                                                <form method="post" action="{% url 'posts:djreddit_sub' category.title %}">
                                                    {% csrf_token %}
                                                    <button class="btn btn-outline-primary" name="sub" value="unsubscribed">Unsubscribe</button>
                                                </form>
                                                {% else %}
                                                <form method="post" action="{% url 'posts:djreddit_sub' category.title %}">
                                                    {% csrf_token %}
                                                    <button class="btn btn-outline-primary" name="sub" value="subscribed">Subscribe</button>
                                                </form>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <script
                                            src="https://code.jquery.com/jquery-3.3.1.min.js"
                                            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                                            crossorigin="anonymous"></script>
                                        {% endfor %}
                                    </ul>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    </body>
</html>